In [49]:
!ls data

items_carsales_13.csv	items_carsales_4.csv
items_carsales_16.json	items_carsales_9.csv

In [2]:
import pandas as pd

In [74]:
filename = 'data/items_carsales_16.csv'
data = pd.read_csv(filename)

In [75]:
data.head()

,_type,drive_type,engine_capacity,fuel_type,id,make,manufacturer_marketing_year,model,n_cylinders,odometer,price,title,transmission,url,year
0,DealFinderItem,NaN,1.8,Petrol,NaN,Holden,NaN,Trax LS TJ,4,80,18990,2017 Holden Trax LS TJ Manual,Manual,carsales.com.au/demo/details/Holden-Trax-2017/...,2017
1,DealFinderItem,NaN,2.0,Petrol,Jeep-Patriot-2016/OAG-AD-16099954,Jeep,NaN,Patriot Sport,4,3041,19990,2016 Jeep Patriot Sport Auto 4x2,Auto,carsales.com.au/dealer/details/Jeep-Patriot-20...,2016
2,DealFinderItem,NaN,1.8,Petrol,NaN,Holden,NaN,Trax LS TJ,4,5000,16000,2016 Holden Trax LS TJ Auto,Auto,carsales.com.au/private/details/Holden-Trax-20...,2016
3,DealFinderItem,2WD,2.0,Petrol,NaN,Peugeot,NaN,4008 Active,4,7600,19990,2016 Peugeot 4008 Active Auto 2WD,Auto,carsales.com.au/private/details/Peugeot-4008-2...,2016
4,DealFinderItem,2WD,2.0,Petrol,SsangYong-Korando-2015/OAG-AD-15997595,SsangYong,NaN,Korando S,4,9408,17990,2015 SsangYong Korando S Manual 2WD,Manual,carsales.com.au/dealer/details/SsangYong-Koran...,2015

In [7]:
data.iloc[3].url

'carsales.com.au/private/details/Peugeot-4008-2016/SSE-AD-5441471/?Cr=3'

In [10]:
# add field for price per kilometer on odometer
data['price_p_km'] = data['price']/data['odometer']
data.head()

,_type,drive_type,engine_capacity,fuel_type,id,make,manufacturer_marketing_year,model,n_cylinders,odometer,price,title,transmission,url,year,price_p_km
0,DealFinderItem,NaN,1.8,Petrol,NaN,Holden,NaN,Trax LS TJ,4,80,18990,2017 Holden Trax LS TJ Manual,Manual,carsales.com.au/demo/details/Holden-Trax-2017/...,2017,237.375000
1,DealFinderItem,NaN,2.0,Petrol,Jeep-Patriot-2016/OAG-AD-16099954,Jeep,NaN,Patriot Sport,4,3041,19990,2016 Jeep Patriot Sport Auto 4x2,Auto,carsales.com.au/dealer/details/Jeep-Patriot-20...,2016,6.573496
2,DealFinderItem,NaN,1.8,Petrol,NaN,Holden,NaN,Trax LS TJ,4,5000,16000,2016 Holden Trax LS TJ Auto,Auto,carsales.com.au/private/details/Holden-Trax-20...,2016,3.200000
3,DealFinderItem,2WD,2.0,Petrol,NaN,Peugeot,NaN,4008 Active,4,7600,19990,2016 Peugeot 4008 Active Auto 2WD,Auto,carsales.com.au/private/details/Peugeot-4008-2...,2016,2.630263
4,DealFinderItem,2WD,2.0,Petrol,SsangYong-Korando-2015/OAG-AD-15997595,SsangYong,NaN,Korando S,4,9408,17990,2015 SsangYong Korando S Manual 2WD,Manual,carsales.com.au/dealer/details/SsangYong-Koran...,2015,1.912202

# Data cleaning
Apply some fine-grained filtering

In [85]:
def clean(data):
    odo_max = 60000
    age_max = 5
    price_max = 16000
    exclude_brands = ['Peugeot', 'Holden', 'SKODA', 'Ford', 'Great', 'Jeep', 'Chery']
    drop_cols = ['manufacturer_marketing_year', 'title', '_type', 'id']

    initial_len = data.shape[0]
    print("Initial num of records: ", initial_len)

    data = pd.read_csv(filename)
    df = data
    df = data[data['odometer'] <= odo_max]
    df = df[df['price'] <= price_max]
    df = df[df['year'] >= 2018-age_max]
    brand_mask = df['make'].isin(exclude_brands)
    df = df[~brand_mask]
    df = df.drop(drop_cols, axis=1)

    final_len = df.shape[0]
    print("Final num of records: ", final_len)
    
    return df

In [70]:
# find average price per make/model
df = clean(data)
df.groupby(['make', 'model']).agg(['mean', 'count']).sort_values(by=('price', 'mean'), ascending=True)

                                     engine_capacity       n_cylinders        \
                                                mean count        mean count
make       model
Nissan     X-Trail ST T31                        2.0     1           4     1
Suzuki     S-Cross GL                            1.6     3           4     3
SsangYong  Korando SX                            2.0     2           4     2
Mitsubishi ASX LS XB                             2.0     1           4     1
Suzuki     S-Cross GLX                           1.6     1           4     1
Nissan     JUKE ST-S F15                         1.6     1           4     1
Kia        Sportage Si                           2.0     3           4     3
Nissan     Dualis ST J10 Series 4                2.0     4           4     4
           Dualis +2 ST J10 Series 4             2.0     1           4     1
           JUKE ST F15                           1.6     3           4     3
           Dualis TS J10 Series 4                1.6     1           4     1
           Dualis ST J10 Series 3                2.0     1           4     1
Mitsubishi ASX XB                                2.0     1           4     1

                                          odometer               price        \
                                              mean count          mean count
make       model
Nissan     X-Trail ST T31             45115.000000     1  13990.000000     1
Suzuki     S-Cross GL                 50244.666667     3  14316.333333     3
SsangYong  Korando SX                 19300.000000     2  14490.000000     2
Mitsubishi ASX LS XB                  50000.000000     1  14890.000000     1
Suzuki     S-Cross GLX                51822.000000     1  14990.000000     1
Nissan     JUKE ST-S F15              44497.000000     1  15213.000000     1
Kia        Sportage Si                49878.333333     3  15288.000000     3
Nissan     Dualis ST J10 Series 4     45617.500000     4  15369.500000     4
           Dualis +2 ST J10 Series 4  32876.000000     1  15500.000000     1
           JUKE ST F15                43072.666667     3  15548.333333     3
           Dualis TS J10 Series 4     35900.000000     1  15900.000000     1
           Dualis ST J10 Series 3     38000.000000     1  15990.000000     1
Mitsubishi ASX XB                     34027.000000     1  15997.000000     1

                                             year
                                             mean count
make       model
Nissan     X-Trail ST T31             2013.000000     1
Suzuki     S-Cross GL                 2014.000000     3
SsangYong  Korando SX                 2015.000000     2
Mitsubishi ASX LS XB                  2014.000000     1
Suzuki     S-Cross GLX                2014.000000     1
Nissan     JUKE ST-S F15              2013.000000     1
Kia        Sportage Si                2013.333333     3
Nissan     Dualis ST J10 Series 4     2013.000000     4
           Dualis +2 ST J10 Series 4  2013.000000     1
           JUKE ST F15                2013.333333     3
           Dualis TS J10 Series 4     2013.000000     1
           Dualis ST J10 Series 3     2013.000000     1
Mitsubishi ASX XB                     2013.000000     1

In [71]:
# add field for price per kilometer on odometer (non-agg)
df = clean(data)
df['pricepkm'] = df['price'] / df['odometer']
df.sort_values(['pricepkm'])

,drive_type,engine_capacity,fuel_type,make,model,n_cylinders,odometer,price,transmission,url,year,pricepkm
262,NaN,1.6,Petrol,Suzuki,S-Cross GL,4,49800,11990,Auto,carsales.com.au/private/details/Suzuki-S-Cross...,2014,0.240763
314,2WD,1.6,Petrol,Nissan,JUKE ST F15,4,53670,14895,Manual,carsales.com.au/dealer/details/Nissan-JUKE-201...,2013,0.277529
301,2WD,2.0,Petrol,Nissan,Dualis ST J10 Series 4,4,52452,14990,Auto,carsales.com.au/dealer/details/Nissan-Dualis-2...,2013,0.285785
290,NaN,2.0,Petrol,Kia,Sportage Si,4,51850,14976,Manual,carsales.com.au/dealer/details/Kia-Sportage-20...,2013,0.288833
289,NaN,1.6,Petrol,Suzuki,S-Cross GLX,4,51822,14990,Auto,carsales.com.au/dealer/details/Suzuki-S-Cross-...,2014,0.289259
287,NaN,1.6,Petrol,Suzuki,S-Cross GL,4,51677,14960,Auto,carsales.com.au/dealer/details/Suzuki-S-Cross-...,2013,0.289490
265,2WD,2.0,Petrol,Mitsubishi,ASX LS XB,4,50000,14890,Manual,carsales.com.au/private/details/Mitsubishi-ASX...,2014,0.297800
258,NaN,2.0,Petrol,Kia,Sportage Si,4,49285,14888,Manual,carsales.com.au/dealer/details/Kia-Sportage-20...,2013,0.302080
205,2WD,2.0,Petrol,Nissan,X-Trail ST T31,4,45115,13990,Manual,carsales.com.au/dealer/details/Nissan-X-Trail-...,2013,0.310096
277,2WD,2.0,Petrol,Nissan,Dualis ST J10 Series 4,4,50725,15888,Auto,carsales.com.au/dealer/details/Nissan-Dualis-2...,2013,0.313218
257,NaN,1.6,Petrol,Suzuki,S-Cross GL,4,49257,15999,Auto,carsales.com.au/dealer/details/Suzuki-S-Cross-...,2015,0.324807
246,2WD,2.0,Petrol,Kia,Sportage Si,4,48500,16000,Manual,carsales.com.au/private/details/Kia-Sportage-2...,2014,0.329897
220,2WD,2.0,Petrol,Nissan,Dualis ST J10 Series 4,4,46293,15800,Auto,carsales.com.au/dealer/details/Nissan-Dualis-2...,2013,0.341304
194,2WD,1.6,Petrol,Nissan,JUKE ST-S F15,4,44497,15213,Manual,carsales.com.au/dealer/details/Nissan-JUKE-201...,2013,0.341888
160,2WD,1.6,Petrol,Nissan,JUKE ST F15,4,41918,15800,Auto,carsales.com.au/dealer/details/Nissan-JUKE-201...,2014,0.376926
121,2WD,2.0,Petrol,Nissan,Dualis ST J10 Series 3,4,38000,15990,Auto,carsales.com.au/dealer/details/Nissan-Dualis-2...,2013,0.420789
103,2WD,1.6,Diesel,Nissan,Dualis TS J10 Series 4,4,35900,15900,Manual,carsales.com.au/private/details/Nissan-Dualis-...,2013,0.442897
72,2WD,2.0,Petrol,Nissan,Dualis ST J10 Series 4,4,33000,14800,Manual,carsales.com.au/private/details/Nissan-Dualis-...,2013,0.448485
83,2WD,2.0,Petrol,Mitsubishi,ASX XB,4,34027,15997,Auto,carsales.com.au/dealer/details/Mitsubishi-ASX-...,2013,0.470127
71,2WD,2.0,Petrol,Nissan,Dualis +2 ST J10 Series 4,4,32876,15500,Auto,carsales.com.au/private/details/Nissan-Dualis-...,2013,0.471469
77,2WD,1.6,Petrol,Nissan,JUKE ST F15,4,33630,15950,Auto,carsales.com.au/dealer/details/Nissan-JUKE-201...,2013,0.474279
15,2WD,2.0,Petrol,SsangYong,Korando SX,4,20461,14490,Auto,carsales.com.au/dealer/details/SsangYong-Koran...,2015,0.708177
11,2WD,2.0,Petrol,SsangYong,Korando SX,4,18139,14490,Auto,carsales.com.au/dealer/details/SsangYong-Koran...,2015,0.798831

In [88]:
# work out value sum (non-agg)
from sklearn.preprocessing import MinMaxScaler

df = clean(data)
df['age'] = 2018 - df['year']

scaler = MinMaxScaler() 
normalize = ['age', 'price', 'odometer', 'engine_capacity']
normalized = [name + '_norm' for name in normalize]
df[normalized] = df[normalize]
df[normalized] = scaler.fit_transform(df[normalized])
df

df['value'] = 0.3*df['price_norm'] + 0.3*df['odometer_norm']+ 0.2*df['age_norm'] + 0.2/df['engine_capacity_norm']
df.sort_values(['value'], ascending=True)
df.drop(normalized, axis=1)
pd.set_option('display.max_colwidth', -1)
df

Initial num of records:  336
Final num of records:  23

,drive_type,engine_capacity,fuel_type,make,model,n_cylinders,odometer,price,transmission,url,year,age,age_norm,price_norm,odometer_norm,engine_capacity_norm,value
11,2WD,2.0,Petrol,SsangYong,Korando SX,4,18139,14490,Auto,carsales.com.au/dealer/details/SsangYong-Korando-2015/OAG-AD-15425454/?Cr=11,2015,3,0.0,0.623441,0.000000,1.0,0.387032
15,2WD,2.0,Petrol,SsangYong,Korando SX,4,20461,14490,Auto,carsales.com.au/dealer/details/SsangYong-Korando-2015/OAG-AD-15793670/?Cr=15,2015,3,0.0,0.623441,0.065351,1.0,0.406638
71,2WD,2.0,Petrol,Nissan,Dualis +2 ST J10 Series 4,4,32876,15500,Auto,carsales.com.au/private/details/Nissan-Dualis-2013/SSE-AD-5514896/?Cr=71,2013,5,1.0,0.875312,0.414765,1.0,0.787023
72,2WD,2.0,Petrol,Nissan,Dualis ST J10 Series 4,4,33000,14800,Manual,carsales.com.au/private/details/Nissan-Dualis-2013/SSE-AD-5425490/?Cr=72,2013,5,1.0,0.700748,0.418254,1.0,0.735701
77,2WD,1.6,Petrol,Nissan,JUKE ST F15,4,33630,15950,Auto,carsales.com.au/dealer/details/Nissan-JUKE-2013/OAG-AD-16140038/?Cr=77,2013,5,1.0,0.987531,0.435985,0.0,inf
83,2WD,2.0,Petrol,Mitsubishi,ASX XB,4,34027,15997,Auto,carsales.com.au/dealer/details/Mitsubishi-ASX-2013/OAG-AD-16117525/?Cr=83,2013,5,1.0,0.999252,0.447159,1.0,0.833923
103,2WD,1.6,Diesel,Nissan,Dualis TS J10 Series 4,4,35900,15900,Manual,carsales.com.au/private/details/Nissan-Dualis-2013/SSE-AD-5521792/?Cr=103,2013,5,1.0,0.975062,0.499873,0.0,inf
121,2WD,2.0,Petrol,Nissan,Dualis ST J10 Series 3,4,38000,15990,Auto,carsales.com.au/dealer/details/Nissan-Dualis-2013/OAG-AD-16210038/?Cr=121,2013,5,1.0,0.997506,0.558977,1.0,0.866945
160,2WD,1.6,Petrol,Nissan,JUKE ST F15,4,41918,15800,Auto,carsales.com.au/dealer/details/Nissan-JUKE-2014/OAG-AD-16033826/?Cr=160,2014,4,0.5,0.950125,0.669247,0.0,inf
194,2WD,1.6,Petrol,Nissan,JUKE ST-S F15,4,44497,15213,Manual,carsales.com.au/dealer/details/Nissan-JUKE-2013/OAG-AD-16109240/?Cr=194,2013,5,1.0,0.803741,0.741831,0.0,inf
205,2WD,2.0,Petrol,Nissan,X-Trail ST T31,4,45115,13990,Manual,carsales.com.au/dealer/details/Nissan-X-Trail-2013/OAG-AD-16173892/?Cr=205,2013,5,1.0,0.498753,0.759224,1.0,0.777393
220,2WD,2.0,Petrol,Nissan,Dualis ST J10 Series 4,4,46293,15800,Auto,carsales.com.au/dealer/details/Nissan-Dualis-2013/OAG-AD-16067021/?Cr=220,2013,5,1.0,0.950125,0.792378,1.0,0.922751
246,2WD,2.0,Petrol,Kia,Sportage Si,4,48500,16000,Manual,carsales.com.au/private/details/Kia-Sportage-2014/SSE-AD-5463331/?Cr=246,2014,4,0.5,1.000000,0.854493,1.0,0.856348
257,NaN,1.6,Petrol,Suzuki,S-Cross GL,4,49257,15999,Auto,carsales.com.au/dealer/details/Suzuki-S-Cross-2015/OAG-AD-16100010/?Cr=257,2015,3,0.0,0.999751,0.875799,0.0,inf
258,NaN,2.0,Petrol,Kia,Sportage Si,4,49285,14888,Manual,carsales.com.au/dealer/details/Kia-Sportage-2013/OAG-AD-15995852/?Cr=258,2013,5,1.0,0.722693,0.876587,1.0,0.879784
262,NaN,1.6,Petrol,Suzuki,S-Cross GL,4,49800,11990,Auto,carsales.com.au/private/details/Suzuki-S-Cross-2014/SSE-AD-5495277/?Cr=262,2014,4,0.5,0.000000,0.891081,0.0,inf
265,2WD,2.0,Petrol,Mitsubishi,ASX LS XB,4,50000,14890,Manual,carsales.com.au/private/details/Mitsubishi-ASX-2014/SSE-AD-5237147/?Cr=265,2014,4,0.5,0.723192,0.896710,1.0,0.785971
277,2WD,2.0,Petrol,Nissan,Dualis ST J10 Series 4,4,50725,15888,Auto,carsales.com.au/dealer/details/Nissan-Dualis-2013/OAG-AD-16139912/?Cr=277,2013,5,1.0,0.972070,0.917115,1.0,0.966755
287,NaN,1.6,Petrol,Suzuki,S-Cross GL,4,51677,14960,Auto,carsales.com.au/dealer/details/Suzuki-S-Cross-2013/OAG-AD-16090380/?Cr=287,2013,5,1.0,0.740648,0.943908,0.0,inf
289,NaN,1.6,Petrol,Suzuki,S-Cross GLX,4,51822,14990,Auto,carsales.com.au/dealer/details/Suzuki-S-Cross-2014/OAG-AD-15977172/?Cr=289,2014,4,0.5,0.748130,0.947989,0.0,inf
290,NaN,2.0,Petrol,Kia,Sportage Si,4,51850,14976,Manual,carsales.com.au/dealer/details/Kia-Sportage-2013/OAG-AD-16132811/?Cr=290,2013,5,1.0,0.744638,0.948777,1.0,0.908025
301,2WD,2.0,Petrol,Nissan,Dualis ST J10 Series 4,4,52452,14990,Auto,carsales.com.au/dealer/details/Nissan-Dualis-2013/OAG-AD-16065843/?Cr=301,2013,5,1.0,0.748130,0.965720,1.0,0.914155
314,2WD,1.6,Petrol,Nissan,JUKE ST F15,4,53670,14895,Manual,carsales.com.au/dealer/details/Nissan-JUKE-2013/OAG-AD-16163339/?Cr=314,2013,5,1.0,0.724439,1.000000,0.0,inf